from datetime import date

def today():
    """Returns today's date as a string in the format YYYY-MM-DD."""
    return date.today().isoformat()

def bullet_list(items):
    """Convert a list of strings into a Markdown bullet list.
 
    ['First point', 'Second point']
    becomes:
    - First point
    - Second point
 
    Returns empty string if the list is empty.
    """
    if not items:
        return ''
    return '\n'.join(f'- {item}' for item in items)
 
def chapters_list(chapters):
    """Convert the chapters array into a simple numbered list.
 
    [{'title': 'Intro'}, {'title': 'Main concept'}]
    becomes:
    1. Intro
    2. Main concept
    """
    if not chapters:
        return ''
    return '\n'.join(
        f'{i}. {ch["title"]}' for i, ch in enumerate(chapters, start=1)
    )
 
 
def format_note(title, channel, url, note):
    """Build the complete Markdown string for an Obsidian note.
 
    Args:
        title: Video title (from YouTube API)
        channel: Channel name (from YouTube API)
        url: Original YouTube URL
        note: The parsed dict from Claude containing:
              tags, summary, keyTakeaways, analogies,
              actionableSteps, chapters
 
    Returns:
        A complete Markdown string ready to write to a file.
    """
    current_date = today()
 
    # Format tags for the frontmatter — e.g. [python, cli, tutorial]
    tags_str = ', '.join(note['tags'])
 
    # Start building the Markdown string
    # The frontmatter goes between --- fences at the top
    md = f"""---
title: "{title}"
channel: "{channel}"
url: "{url}"
date: "{current_date}"
tags: [{tags_str}]
---
 
## 📝 Summary
 
{note['summary']}
 
## 💡 Key Takeaways
 
{bullet_list(note['keyTakeaways'])}
"""
 
    # Analogies section — only include if Claude found complex concepts
    if note.get('analogies'):
        md += f"""
## 👨🏽‍🏫 Analogies
 
{bullet_list(note['analogies'])}
"""
 
    # Actionable steps — only include if the video had practical advice
    if note.get('actionableSteps'):
        md += f"""
## 🪖 Actionable Steps / Project Ideas
 
{bullet_list(note['actionableSteps'])}
"""
 
    # Chapters section — always present
    md += f"""
## 📖 Chapters
 
{chapters_list(note['chapters'])}
 
---
*Generated by yt-note on {current_date}*
"""
 
    return md
 