import argparse
import sys
from pathlib import Path
from config import config_exists, load_config, prompt_for_config
from transcript import fetch_transcript
from ai import generate_note, rank_related_notes
from format import format_note
from save import save_note
from batch import load_urls, process_batch, print_batch_summary
from cost import record_usage, format_cost_report, estimate_cost
from linker import scan_vault, keyword_filter, insert_inline_links, build_related_section, append_backlink, display_proposed_links
from search import run_search
from ui import Spinner, print_banner, RED, PURPLE, GREEN, RESET

def parse_args():
    parser = argparse.ArgumentParser(description = 'Turn Youtube videos into Obisdian notes')

    parser.add_argument(
        'url',
        nargs = '?',
        help = 'Youtube video URL'
    )

    parser.add_argument(
        '--batch',
        help = 'Path to a text file containing multiple Youtube URLs (one per line)'
    )

    parser.add_argument(
        '--ask',
        help='Ask a question across your knowledge base'
    )

    args = parser.parse_args()

    if not args.url and not args.batch and not args.ask:
        parser.print_help()
        print(f'\n{RED}Error: Provide a single URL or use --batch <file>{RESET}')
        sys.exit(1)
    
    return args

def process_single_url(url, config):
    with Spinner('Fetching transcipt...', colour = RED) as sp:
        data = fetch_transcript(url, config['youtube_api_key'])
        sp.stop(f'Transcript fetched ({data["word_count"]} words)')

    est = estimate_cost(data['transcript'])
    print(f'\n💰 Estimated cost: ~${est["estimated_cost"]:.4f}')
    confirm = input('   Continue? [Y/n] ').strip().lower()
    if confirm  == 'n':
        print('👍 Cancelled by user.')
        return

    with Spinner('Generating note with Claude...', colour = PURPLE) as sp:
        result = generate_note(
            api_key = config['api_key'],
            title = data['title'],
            channel = data['channel'],
            transcript = data['transcript'],
            word_count = data['word_count']
        )

        note = result['note']
        usage = result['usage']
        sp.stop('Note generated')

    markdown = format_note(
        title = data['title'],
        channel = data['channel'],
        url = url,
        note = note
    )

    with Spinner('Saving to vault...', colour = PURPLE) as sp:  
        filepath = save_note(
            vault_path = config['vault_path'],
            title = data['title'],
            tags = note['tags'],
            markdown = markdown
        )
        sp.stop(f'Done! Saved to: {filepath}')

    from embedder import store_embedding
    with Spinner('Embedding note for search...', colour = PURPLE) as sp:
        store_embedding(filepath, data['title'], note['summary'])
        sp.stop('Note embedded')
    
    stats = record_usage(usage['input_tokens'], usage['output_tokens'])
    print(f'\n{format_cost_report(stats)}')

    link_candidates = config.get('link_candidates', 15)

    with Spinner('Scanning vault for related notes...', colour = PURPLE) as sp:
        existing_notes = scan_vault(config['vault_path'])
        sp.stop(f'Found {len(existing_notes)} existing notes')

        if not existing_notes:
            print('No suitable candiates found for linking. Skipping link generation.')
            return
        
        candidates = keyword_filter(
            new_note = {'title' : data['title'], 'tags' : note['tags']},
            existing_notes = existing_notes,
            max_candidates = link_candidates
        )

        if not candidates:
            print('No related notes found for linking. Skipping link generation.')
            return
        
    with Spinner('Finding related notes...', colour = PURPLE) as sp:
        link_result = rank_related_notes(
            api_key=config['api_key'],
            new_note_summary=note['summary'],
            new_note_title=data['title'],
            new_note_tags=note['tags'],
            candidates=candidates
        )
        sp.stop(f'Found {len(link_result["links"])} related notes')

    link_stats = record_usage(
        link_result['usage']['input_tokens'],   
        link_result['usage']['output_tokens']
    )
    print(f'Linking cost: ${link_stats["call_cost"]:.4f}')

    if not link_result['links']:
        print(' No strong connections found -- Skipping link generation')
        return
    
    if not display_proposed_links(link_result['links']):
        print('👍 Linking cancelled by user.')
        return
    
    saved_text = Path(filepath).read_text(encoding = 'utf-8')
    linked_titles = [link['title'] for link in link_result['links']]

    updated_text = insert_inline_links(saved_text, linked_titles)

    related_section = build_related_section(link_result['links'])
    footer_marker = '---\n*Generated by Obsiditube'
    if footer_marker in updated_text:
        updated_text = updated_text.replace(footer_marker, f'{related_section}\n\n{footer_marker}')
    else:
        updated_text += f'\n\n{related_section}'

    Path(filepath).write_text(updated_text, encoding = 'utf-8')

    for link in link_result['links']:
        if link.get('path'):
            append_backlink(link['path'], data['title'])

    print(f'{GREEN}✅ Links applied and {len(link_result["links"])} existing notes updated{RESET}')

def main():
    """Main function — runs the full pipeline from URL to saved note."""

    print_banner()

    args = parse_args()

    if config_exists():
        config = load_config()
    else:
        config = prompt_for_config()

    if args.ask:
        run_search(args.ask, config)
    elif args.batch:
        urls = load_urls(args.batch)
        print(f' Loaded {len(urls)} URLs from {args.batch} \n')
        results = process_batch(urls, config)
        print_batch_summary(results)
    else:
        process_single_url(args.url, config)

if __name__ == '__main__':
    try:
        main()
    except KeyboardInterrupt:
        print(f'\n Cancelled')
        sys.exit(0)
    except Exception as err:
        print(f'\n{RED}❌ Error: {err}{RESET}')
        sys.exit(1)