# stop_words.py
# Common English words that carry no topical meaning.
# Used by the keyword filter in linker.py to skip words
# that would cause false matches between notes.
#
# These are words that appear in almost any text regardless
# of topic — filtering them out means only meaningful words
# like "investing", "python", "decorators" get compared.
#
# Add new words here as you discover false matches.
# Generated by Claude.

STOP_WORDS = {
    # Articles and determiners
    'the', 'a', 'an', 'this', 'that', 'these', 'those',

    # Pronouns
    'i', 'you', 'he', 'she', 'it', 'we', 'they',
    'me', 'him', 'her', 'us', 'them',
    'my', 'your', 'his', 'its', 'our', 'their',
    'myself', 'yourself', 'himself', 'herself', 'itself',

    # Conjunctions and connectors
    'and', 'but', 'or', 'nor', 'for', 'yet', 'so',
    'however', 'because', 'although', 'though', 'while',
    'therefore', 'moreover', 'furthermore', 'nevertheless',
    'meanwhile', 'otherwise', 'instead',

    # Prepositions
    'in', 'on', 'at', 'to', 'of', 'by', 'up',
    'with', 'from', 'into', 'about', 'between',
    'through', 'during', 'before', 'after', 'without',
    'above', 'below', 'under', 'over', 'around',

    # Common verbs (non-topical)
    'is', 'am', 'are', 'was', 'were', 'be', 'been', 'being',
    'have', 'has', 'had', 'do', 'does', 'did', 'doing',
    'will', 'would', 'could', 'should', 'shall', 'might',
    'can', 'may', 'must',
    'get', 'got', 'make', 'made', 'let', 'say', 'said',
    'know', 'think', 'want', 'need', 'look', 'give', 'take',
    'come', 'go', 'going', 'went', 'keep', 'tell', 'told',
    'find', 'found', 'put', 'run', 'see', 'seem',

    # Adverbs
    'not', 'just', 'also', 'very', 'really', 'actually',
    'still', 'even', 'only', 'already', 'always', 'never',
    'often', 'sometimes', 'again', 'here', 'there',
    'now', 'then', 'when', 'where', 'how', 'what',
    'why', 'which', 'who', 'whom', 'whose',
    'much', 'more', 'most', 'well', 'back',

    # Quantifiers and numbers
    'all', 'some', 'any', 'many', 'few', 'each', 'every',
    'both', 'other', 'another', 'such', 'no', 'one', 'two',
    'first', 'last', 'next',

    # Common filler words in video titles and transcripts
    'like', 'thing', 'things', 'stuff', 'way', 'ways',
    'people', 'something', 'everything', 'nothing',
    'everyone', 'anyone', 'someone',
    'today', 'right', 'sure', 'okay', 'yeah',
    'video', 'watch', 'channel', 'subscribe',
}