# test_linker.py
# Tests for the linking feature.
# Run with: python -m unittest test_linker.py
#
# These tests don't call the Claude API — they only test the
# free, local functions (scanning, filtering, link insertion,
# backlinks). The Claude ranking is tested separately if needed.

import unittest
import tempfile
from pathlib import Path
from linker import (
    parse_frontmatter,
    scan_vault,
    keyword_filter,
    insert_inline_links,
    build_related_section,
    append_backlink
)


def create_test_note(folder, filename, title, tags, body='Some content here.'):
    """Helper to create a fake note file for testing.

    Not a test itself — just a utility that multiple tests use.
    Creates a properly formatted .md file with frontmatter.
    """
    tags_str = ', '.join(tags)
    content = f"""---
title: "{title}"
channel: "Test Channel"
url: "https://youtube.com/test"
date: "2026-04-27"
tags: [{tags_str}]
---

## 📝 Summary

{body}

---
*Generated by yt-note on 2026-04-27*
"""
    filepath = Path(folder) / filename
    filepath.parent.mkdir(parents=True, exist_ok=True)
    filepath.write_text(content, encoding='utf-8')
    return filepath


class TestParseFrontmatter(unittest.TestCase):
    """Tests for extracting title and tags from note frontmatter."""

    def test_valid_frontmatter(self):
        """Should extract title and tags from a properly formatted note."""
        with tempfile.TemporaryDirectory() as tmp:
            filepath = create_test_note(
                tmp, 'test.md',
                title='How Compound Interest Works',
                tags=['finance', 'investing']
            )
            result = parse_frontmatter(filepath)

            self.assertEqual(result['title'], 'How Compound Interest Works')
            self.assertEqual(result['tags'], ['finance', 'investing'])

    def test_missing_frontmatter(self):
        """Should return None if the file has no --- fences."""
        with tempfile.TemporaryDirectory() as tmp:
            filepath = Path(tmp) / 'no_frontmatter.md'
            filepath.write_text('Just some text, no frontmatter.')

            result = parse_frontmatter(filepath)
            self.assertIsNone(result)

    def test_empty_tags(self):
        """Should handle notes with no tags gracefully."""
        with tempfile.TemporaryDirectory() as tmp:
            filepath = Path(tmp) / 'no_tags.md'
            filepath.write_text('---\ntitle: "Test Note"\n---\nBody here.')

            result = parse_frontmatter(filepath)
            self.assertEqual(result['title'], 'Test Note')
            # Tags key might not exist, that's fine
            self.assertEqual(result.get('tags', []), [])


class TestScanVault(unittest.TestCase):
    """Tests for scanning the vault and finding existing notes."""

    def test_finds_notes_in_subfolders(self):
        """Should find .md files in all category subfolders."""
        with tempfile.TemporaryDirectory() as tmp:
            notes_dir = Path(tmp) / 'Youtube Notes'

            create_test_note(
                notes_dir / 'Finance', 'investing.md',
                title='Index Fund Investing',
                tags=['finance', 'investing']
            )
            create_test_note(
                notes_dir / 'Tech', 'python.md',
                title='Python Decorators',
                tags=['python', 'tutorial']
            )

            results = scan_vault(tmp)
            self.assertEqual(len(results), 2)

            titles = [r['title'] for r in results]
            self.assertIn('Index Fund Investing', titles)
            self.assertIn('Python Decorators', titles)

    def test_empty_vault(self):
        """Should return empty list if YouTube Notes folder doesn't exist."""
        with tempfile.TemporaryDirectory() as tmp:
            results = scan_vault(tmp)
            self.assertEqual(results, [])

    def test_ignores_non_md_files(self):
        """Should only pick up .md files, ignore everything else."""
        with tempfile.TemporaryDirectory() as tmp:
            notes_dir = Path(tmp) / 'YouTube Notes' / 'Tech'
            notes_dir.mkdir(parents=True)

            # Create an .md file and a .txt file
            create_test_note(
                notes_dir, 'real-note.md',
                title='Real Note', tags=['tech']
            )
            (notes_dir / 'not-a-note.txt').write_text('ignore me')

            results = scan_vault(tmp)
            self.assertEqual(len(results), 1)
            self.assertEqual(results[0]['title'], 'Real Note')


class TestKeywordFilter(unittest.TestCase):
    """Tests for the keyword-based candidate filtering."""

    def test_matches_shared_tags(self):
        """Notes with shared tags should be returned as candidates."""
        new_note = {'title': 'ETF Investing Guide', 'tags': ['finance', 'etf']}
        existing = [
            {'title': 'Dollar Cost Averaging', 'tags': ['finance', 'investing'], 'path': '/a.md', 'filename': 'a'},
            {'title': 'Python Basics', 'tags': ['python', 'tutorial'], 'path': '/b.md', 'filename': 'b'},
        ]

        results = keyword_filter(new_note, existing, max_candidates=10)

        # Only the finance note should match
        self.assertEqual(len(results), 1)
        self.assertEqual(results[0]['title'], 'Dollar Cost Averaging')

    def test_skips_self(self):
        """Should not match a note against itself."""
        new_note = {'title': 'Python Basics', 'tags': ['python']}
        existing = [
            {'title': 'Python Basics', 'tags': ['python'], 'path': '/a.md', 'filename': 'a'},
            {'title': 'Python Advanced', 'tags': ['python'], 'path': '/b.md', 'filename': 'b'},
        ]

        results = keyword_filter(new_note, existing, max_candidates=10)

        titles = [r['title'] for r in results]
        self.assertNotIn('Python Basics', titles)
        self.assertIn('Python Advanced', titles)

    def test_respects_max_candidates(self):
        """Should return at most max_candidates results."""
        new_note = {'title': 'Finance', 'tags': ['finance']}
        existing = [
            {'title': f'Note {i}', 'tags': ['finance'], 'path': f'/{i}.md', 'filename': str(i)}
            for i in range(20)
        ]

        results = keyword_filter(new_note, existing, max_candidates=5)
        self.assertEqual(len(results), 5)

    def test_no_matches(self):
        """Should return empty list when nothing matches."""
        new_note = {'title': 'Cooking Pasta', 'tags': ['cooking']}
        existing = [
            {'title': 'Python Basics', 'tags': ['python'], 'path': '/a.md', 'filename': 'a'},
        ]

        results = keyword_filter(new_note, existing, max_candidates=10)
        self.assertEqual(results, [])


class TestInsertInlineLinks(unittest.TestCase):
    """Tests for inserting [[wiki links]] into note body text."""

    def test_links_first_mention_only(self):
        """Should only wrap the first occurrence in [[links]]."""
        markdown = """---
title: "Test"
---

Python decorators are great. I love decorators."""

        result = insert_inline_links(markdown, ['decorators'])

        # First mention linked, second left alone
        self.assertIn('[[decorators]]', result)
        # Count occurrences — should be exactly one [[link]]
        self.assertEqual(result.count('[[decorators]]'), 1)
        # The second "decorators" should still be there unlinked
        self.assertIn('I love decorators.', result)

    def test_does_not_link_in_frontmatter(self):
        """Should never insert links inside the --- frontmatter block."""
        markdown = """---
title: "Python Decorators Guide"
tags: [python, decorators]
---

This note covers decorators."""

        result = insert_inline_links(markdown, ['decorators'])

        # Frontmatter should be untouched
        self.assertIn('tags: [python, decorators]', result)

    def test_case_insensitive_matching(self):
        """Should match regardless of capitalisation."""
        markdown = """---
title: "Test"
---

Understanding Compound Interest is important."""

        result = insert_inline_links(markdown, ['compound interest'])
        self.assertIn('[[compound interest]]', result.lower())

    def test_no_match_found(self):
        """Should return unchanged markdown if the title doesn't appear."""
        markdown = """---
title: "Test"
---

This note is about cooking."""

        result = insert_inline_links(markdown, ['quantum physics'])
        self.assertEqual(result, markdown)


class TestBuildRelatedSection(unittest.TestCase):
    """Tests for building the Related Notes markdown section."""

    def test_builds_correct_format(self):
        """Should produce properly formatted markdown with [[links]]."""
        linked = [
            {'title': 'Note A', 'reason': 'shared topic'},
            {'title': 'Note B', 'reason': 'related concept'},
        ]

        result = build_related_section(linked)

        self.assertIn('## Related Notes', result)
        self.assertIn('- [[Note A]] — shared topic', result)
        self.assertIn('- [[Note B]] — related concept', result)

    def test_empty_list(self):
        """Should still have the header even with no links."""
        result = build_related_section([])
        self.assertIn('## Related Notes', result)


class TestAppendBacklink(unittest.TestCase):
    """Tests for adding backlinks to existing notes."""

    def test_adds_new_section_when_none_exists(self):
        """Should create a Related Notes section if the note doesn't have one."""
        with tempfile.TemporaryDirectory() as tmp:
            filepath = create_test_note(
                tmp, 'existing.md',
                title='Existing Note',
                tags=['finance']
            )

            append_backlink(str(filepath), 'New Note Title')

            text = filepath.read_text()
            self.assertIn('## Related Notes', text)
            self.assertIn('- [[New Note Title]]', text)

    def test_appends_to_existing_section(self):
        """Should add to existing Related Notes without replacing."""
        with tempfile.TemporaryDirectory() as tmp:
            filepath = create_test_note(
                tmp, 'existing.md',
                title='Existing Note',
                tags=['finance']
            )

            # Add first backlink
            append_backlink(str(filepath), 'First Link')
            # Add second backlink
            append_backlink(str(filepath), 'Second Link')

            text = filepath.read_text()
            self.assertIn('- [[First Link]]', text)
            self.assertIn('- [[Second Link]]', text)

    def test_no_duplicate_backlinks(self):
        """Should not add the same backlink twice."""
        with tempfile.TemporaryDirectory() as tmp:
            filepath = create_test_note(
                tmp, 'existing.md',
                title='Existing Note',
                tags=['finance']
            )

            append_backlink(str(filepath), 'Same Note')
            append_backlink(str(filepath), 'Same Note')

            text = filepath.read_text()
            # Should appear exactly once
            self.assertEqual(text.count('- [[Same Note]]'), 1)


if __name__ == '__main__':
    unittest.main()