import unittest
import tempfile
from pathlib import Path
from linker import (
    parse_frontmatter,
    scan_vault,
    keyword_filter,
    insert_inline_links,
    build_related_section,
    append_backlink,
)

def create_test_note(folder, filename, title, tags, body = 'Some content here. '):
    """Helper to create a fake note file for testing.
 
    Not actual test just a utility that multiple tests use.
    Creates a properly formatted .md file with frontmatter.
    """

    tags_str = ', '.join(tags)
    content = f"""---
title: "{title}"
channel: "Test Channel"
url: "https://youtube.com/test"
date: "2026-04-27"
tags: [{tags_str}]
---
 
## 📝 Summary
 
{body}
 
---
*Generated by yt-note on 2026-04-27*
"""
    filepath = Path(folder) / filename
    filepath.write_text(content, encoding = 'utf-8')
    return filepath

class TestParseFrontmatter(unittest.TestCase):
    """Tests for extracting title and tags from note frontmatter."""

    def test_valid_frontmatter(self):
        with tempfile.TemporaryDirectory() as tmp:
            filepath = create_test_note(
                tmp, 'test.md',
                title = 'How compound interest works',
                tags = ['finance', 'investing']
            )
            result = parse_frontmatter(filepath)

            self.assertEqual(result['title'], 'How compound interest works')
            self.assertEqual(result['tags'], ['finance', 'investing'])

    def test_missing_frontmatter(self):
        """Should return None if the file has no --- fences."""
        with tempfile.TemporaryDirectory() as tmp:
            filepath = Path(tmp) / 'nofrontmatter.md'
            filepath.write_text('Just some text with no frontmatter.')

            result = parse_frontmatter(filepath)
            self.assertIsNone(result)

    def test_empty_tags(self):
        """Should handle notes with no tags"""
        with tempfile.TemporaryDirectory() as tmp:
            filepath = Path(tmp) / 'notags.md'
            filepath.write_text('---\ntitle: "Test Note "\n---\nBody here.')

            result = parse_frontmatter(filepath)
            self.assertEqual(result['title'], 'Test Note')

            self.assertEqual(result.get('tags', []), [])

